import { ReactNode } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const mani = localFont({
  src: [
    {
      path: "../public/fonts/mj-mani/mj-mani.ttf",
      style: "normal",
    },
  ],
  variable: "--font-mani",
});

export const metadata: Metadata = {
  title: "ZarvanTrip",
  description: "Generated by Iman Khorshidi",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en" dir="rtl">
      <body className={`${inter.variable} ${mani.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
